---

- hosts: localhost
  become: true
  vars_files:
    - vars.yml


  tasks:

  - name: Add the Logstash input configuration for Beats
    template: src=templates/mongodb-input.conf dest=/etc/logstash/conf.d/00-mongodb-input.conf

  - name: Add the Logstash output configuration to Elasticsearch
    template: src=templates/elasticsearch-output.conf dest=/etc/logstash/conf.d/20-elasticsearch-output.conf

  - name: Create the directory for the MongoDB data
    file: path=/var/local/logstash-mongodb/ state=directory owner=logstash group=logstash mode=0755

  - name: Start Logstash
    service: name=logstash state=restarted
