filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/mongodb/mongod.log
  document_type: mongodb


output.logstash:
  hosts: ["localhost:5044"]
  username: "{{ elastic_user }}"
  password: "{{ elastic_password }}"
