heartbeat.monitors:
- type: tcp
  hosts: ["127.0.0.1:27017"]
  schedule: '@every 10s'


output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "{{ elastic_user }}"
  password: "{{ elastic_password }}"
